name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with YARN
        run: yarn install
      
      - name: Install ionic
        run: npm install -g @ionic/cli

      - name: Build the app
        run: npm run build
